package:
  name: venture
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

source:
  path: ../

requirements:
  build:
    - git
    - python 2.7.*
  run:
    - nomkl
    - flask >=0.10
    - jsonschema
    - matplotlib 1.5.*
    - networkx
    - numpy 1.11.*
    - pandas 0.18.*
    - patsy >=0.2
    - python 2.7.*
    - requests >=1.2
    - scipy 0.17.*
    - six 1.10.*

test:
  source_files:
    - test
    - examples
  requires:
    - markdown2 # For building the tutorial with venture-transcript. TODO Is markdown2 a real dependency?
    - matplotlib 1.5.*
    - nose >=1.3
    - pexpect
    - pytest 2.8.*
    - python 2.7.*
    - six 1.10.*
  commands:
    - nosetests -c lite-crashes.cfg -w test -e integration

about:
  home: https://github.com/probcomp/Venturecxx
  license: Apache
  license_file: LICENSE
